
services:
  # backend: 
  #   build: .
  #   volumes:
  #     - .:/app
  #     - node_modules:/app/node_modules
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - db
  #   networks:
  #     - nestjs-network
  #   restart: unless-stopped

  db:
    image: postgres:16.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # networks:
    #   - nestjs-network
    restart: unless-stopped

# networks:
#   nestjs-network:
#     driver: bridge

volumes:
  # node_modules:
  postgres_data: